
blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/stellar-network-builders/wavelum-core/discussions
    about: Ask questions and discuss ideas here.
